#!/bin/bash

PKGNAME="${@: -1}"
OVERRIDE=0

main() {
   checkifroot
   getinput "$@"
   
   if [ $# -eq 0 ] || [[ $PKGNAME == -* ]]; then
      echo "No arguments provided!"
      echo "Program will display help message and exit"
      echo ""
      gethelp
   fi

   if [ -a /etc/portage/package.use/$PKGNAME ] && [ $OVERRIDE -ne 1 ]; then
      $EDITOR /etc/portage/package.use/$PKGNAME
   else
      echo $(getpkg $PKGNAME) > /etc/portage/package.use/$PKGNAME
      $EDITOR /etc/portage/package.use/$PKGNAME
   fi

   exit 0

}

checkifroot() {
   if [[ `echo $EUID` -ne 0 ]]; then
      echo ""
      echo "This script must be run as root!!"
      echo ""
      exit 0
   fi
}

getpkg() {
   if [ `emerge --search $PKGNAME | tail -2 | head -1 | rev | cut -c 2- | rev | cut -d':' -f2 | cut -d' ' -f2` -ne 0 ]; then
      if [ -z `curl -s https://packages.gentoo.org/packages/search?q=$1 | sed '95q;d' | rev | cut -c 3- | rev | cut -d '/' -f3-4` ]; then
         echo `curl -s https://packages.gentoo.org/packages/search?q=$1 | cut -d'/' -f5-6 | cut -d'"' -f1`
      else
         echo `curl -s https://packages.gentoo.org/packages/search?q=$1 | sed '95q;d' | rev | cut -c 3- | rev | cut -d '/' -f3-4`
      fi
   else
      echo "Package not found!"
      echo "The script works only with official gentoo packages (no overlays)"
      exit 0
   fi
}

gethelp() {
   echo "Usage: useconf [OPTIONS] [INPUT]..."
   echo "Edit useflags for a specific package. [INPUT] == package name"
   echo ""
   echo "Options:"
   echo "-o, --override		Overrides existing file"
   echo "-h, --help		Display this screen and exit"
   echo "-u, --use		Display available useflags for the package (requires app-portage/gentoolkit) and exit"
   echo ""
   exit 0
}

printuse() {
   if [[ $PKGNAME == -* ]]; then
      echo "No package specified!"
   else
      echo "Available useflags for package $PKGNAME :"
      echo ""
      equery u $PKGNAME
   fi
   exit 0
}

getinput() {
   for i in $@; do
      if [[ $i == -* ]]; then
         case "$i" in
	    -o|--override) OVERRIDE=1;;
	    -h|--help) gethelp;;
	    -u|--use) printuse;;
	    *)
	       echo "Unknown parameter $i !!"
	       gethelp
	       ;;
	 esac
      fi
      if [ ${i+1} == NULL ]; then
         return 0
      fi
   done       
}

   
main "$@"
